### ISSUE TITLE
Nav Items only created on the first 2nd level menu.

### ISSUE THREAD

**Issue by P3N-101** [ValoIntranet/doctor#41]
On Windows, getting a issue where the 3rd level headings are not being created after the 1st 2nd level heading.

I have the following menu structure in doctor.json
```
"menu": {
        "QuickLaunch": {
          "items": [{
            "id": "bestpractice",
            "name": "Best Practices",
            "url": "",
            "items": [{
                "id": "solutions",
                "name": "Solutions",
                "url": ""
                },
                {
                "id": "canvas",
                "name": "Canvas Apps",
                "url": ""
                },
                {
                "id": "model",
                "name": "Model Driven Apps",
                "url": ""
                }]
            },
            {
            "id": "processes",
            "name": "Processes",
            "url": ""
            },
            {
            "id": "accelerators",
            "name": "Solution Accelerators",
            "url": ""
            }]
        }
    }
```
The following page menu item gets created:
```
menu:
  QuickLaunch:
    name: "Power Platform Default Publisher"
    id: defaultpublisher
    weight: 4
    parent: bestpractice/solutions
```
The following page menu items don't:
```
menu:
  QuickLaunch:
    name: "Control Naming Conventions"
    id: controlnaming
    weight: 4
    parent: bestpractice/canvas
```
or
```
menu:
  QuickLaunch:
    name: "Entity Naming Conventions"
    id: controlnaming
    weight: 4
    parent: bestpractice/model
```
![image](https://user-images.githubusercontent.com/70491094/107159623-442a7000-6989-11eb-9c25-d9019f5dff52.png)
